### ISSUE TITLE
Should be easier to build

### ISSUE THREAD

**Issue by palladius** [esseks/monicelli#29]
Is it possible to have a Makefile or a ./configure?
I'm unable to build on Ubuntu 14.04.

$ sudo apt-get install cmake bison

... e poi?

**Comment by esseks** [comment]
Hi, you can find detailed instructions in the [Compilation](https://github.com/esseks/monicelli#compilation) section of the README. The project follows a standard workflow, where the Makefile is generated using CMake and then run. 

Let me know if there is anything unclear or badly worded.

**Comment by esseks** [comment]
Closing as old/stalled. Feel free to reopen if you have more to discuss.
