### ISSUE TITLE
Can't compile the compiler

### ISSUE THREAD

**Issue by GTP95** [esseks/monicelli#32]
Hi everyone. I was trying to "install" Monicelli on my computer to play with it but I had a problem. First I used `$git clone` to clone your repository into a folder called "monicelli", then I used `$cmake monicelli` to generate the needed configuration and until here, everything went fine. Then I run the `$make` program but it terminated with two errors, here's the full output:

> [giacomo@giacomo-tower ~]$ make
> [  7%] [FLEX][Scanner] Building scanner with flex 2.6.0
> [ 14%] [BISON][Parser] Building parser with bison 3.0.4
> Scanning dependencies of target mcc
> [ 21%] Building CXX object src/CMakeFiles/mcc.dir/main.cpp.o
> [ 28%] Building CXX object src/CMakeFiles/mcc.dir/Nodes.cpp.o
> [ 35%] Building CXX object src/CMakeFiles/mcc.dir/CLineParser.cpp.o
> [ 42%] Building CXX object src/CMakeFiles/mcc.dir/ModuleRegistry.cpp.o
> [ 50%] Building CXX object src/CMakeFiles/mcc.dir/ModuleLoader.cpp.o
> [ 57%] Building CXX object src/CMakeFiles/mcc.dir/Parser.cpp.o
> [ 64%] Building CXX object src/CMakeFiles/mcc.dir/Lexer.cpp.o
> /home/giacomo/src/Lexer.cpp: In member function ‘virtual int monicelli::Scanner::yylex()’:
> /home/giacomo/src/Lexer.cpp:928:23: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
>     for ( yyl = 0; yyl < yyleng; ++yyl )
>                        ^
> At global scope:
> cc1plus: error: unrecognized command line option ‘-Wno-deprecated-register’ [-Werror]
> cc1plus: all warnings being treated as errors
> src/CMakeFiles/mcc.dir/build.make:218: set di istruzioni per l'obiettivo "src/CMakeFiles/mcc.dir/Lexer.cpp.o" non riuscito
> make[2]: **\* [src/CMakeFiles/mcc.dir/Lexer.cpp.o] Errore 1
> CMakeFiles/Makefile2:87: set di istruzioni per l'obiettivo "src/CMakeFiles/mcc.dir/all" non riuscito
> make[1]: **\* [src/CMakeFiles/mcc.dir/all] Errore 2
> Makefile:149: set di istruzioni per l'obiettivo "all" non riuscito
> make: **\* [all] Errore 2

Seems to me that trying to compile using different flags could work, but I'm not sure about what to do. Thanks for your help

**Comment by esseks** [comment]
The latest release should fix this, simply by getting rid of Flex. Please let me know if it works for you.
