### ISSUE TITLE
Cmake lists as NOTFOUND the YAML_INCLUDE_DIRS

### ISSUE THREAD

**Issue by melefabrizio** [esseks/monicelli#37]
I'm running OS X, installed yaml-cpp throug brew. Still even exporting YAML_INCLUDE_DIRS and YAML_LIBRARIES as the specific `/usr/local/Cellar/yaml-cpp/0.5.3/include/yaml-cpp/` and  `/usr/local/Cellar/yaml-cpp/0.5.3/include/lib/`directories, cmake returns 

```
  CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
  Please set them or make sure they are set and tested correctly in the CMake files:
  YAML_INCLUDE_DIRS
   used as include directory in directory /Users/fabrizio/monicelli-master/src
   used as include directory in directory /Users/fabrizio/monicelli-master/src
   used as include directory in directory /Users/fabrizio/monicelli-master/src
   used as include directory in directory /Users/fabrizio/monicelli-master/src
   used as include directory in directory /Users/fabrizio/monicelli-master/src
   used as include directory in directory /Users/fabrizio/monicelli-master/src
   used as include directory in directory /Users/fabrizio/monicelli-master/src
   used as include directory in directory /Users/fabrizio/monicelli-master/src
   used as include directory in directory /Users/fabrizio/monicelli-master/src
```

CMake version is 3.5.1
Yaml-cpp is 0.5.3

**Comment by GTP95** [comment]
I think that the easier way to use monicelli is to use a Vagrant image as dedcribed here: https://github.com/esseks/monicelli/pull/25. I tested it and it works fine. I don't know why the creators of monicelli haven't merged this pull request but seems that's about a year that they don't do any update of the project. I hope they haven't abandoned it.

**Comment by esseks** [comment]
The newest release remove the dependency on YAML (which was part of the rarely used C-Monicelli integration). I'm going to close this issue, but please reopen it if you have further questions.
