### ISSUE TITLE
monicellizer

### ISSUE THREAD

**Issue by buttha** [esseks/monicelli#43]
It would be great to think about a monicelizzer, in order to spread the supercazzola around the source code.
I'd like to translate bitcoin core source code in monicelli source code, in order to explore AntaniCoins world

**Comment by esseks** [comment]
My experience is that automatic code translation is hardly effective at producing _source_ code, and the translated result is best compiled than read. I don't have the resources to start a project like this, but if you do, I'm only going to say, deputy mayor!
