### ISSUE TITLE
Typo or design

### ISSUE THREAD

**Issue by shineangelic** [esseks/monicelli#46]
Supercazzola is for sure the most common and spread spelling of this modernist neologism. But the correct spelling, present on the book, is supercazzora.

**Comment by esseks** [comment]
The initial design choice was to limit the number of reserved keywords in the language by selecting the most common spelling for the centerpiece token in this cofandina. But the chances of someone using `supercazzora` in a context completely unrelated from `supercazzola` are slim, I think it makes sense to add the alternative spelling.

**Comment by esseks** [comment]
The newest release supports `supercazzora` as alternative spelling. Now we are closer to the book.
