### ISSUE TITLE
LLVM 9

### ISSUE THREAD

**Issue by PsykeDady** [esseks/monicelli#48]
non va con llvm perchè richiede la versione 6. Nessun modo di farlo andare con versioni più aggiornate?

[END] doen't work with llvm 9, requested version is 6. Any way to get work with updated version? 
![image](https://user-images.githubusercontent.com/27916449/69901198-0a220f00-137f-11ea-9662-5e69012a270f.png)

**Comment by esseks** [comment]
Monicelli now supports LLVM 7, 8 and 9. CMake looks for 7 by default, so you'll have to replace 7 with 9, here:

https://github.com/esseks/monicelli/blob/439ef31f94d5300fede1eb25a4730c8c819b246a/src/CMakeLists.txt#L4

I'll find a way to make the target LLVM version easier to configure.
